### ISSUE TITLE
Does not build - missing 'inferior-numcl'

### ISSUE THREAD

**Issue by quicklisp** [digikar99/reader#1]
I get this: ` Component "inferior-numcl" not found, required by #<SYSTEM "reader">`

Where can I get inferior-numcl?

**Comment by digikar99** [comment]
Could you pick the [latest release](https://github.com/digikar99/reader/releases) of `reader`? This doesn't require it.

**Comment by digikar99** [comment]
I assume this has been fixed, given that quicklisp has picked it up.
